from cffi import FFI

ffi = FFI()
ffi.cdef("bool x86_inc_r16(reg, void**);")
ffi.cdef("bool x86_inc_r32(reg, void**);")
ffi.cdef("bool x86_dec_r16(reg, void**);")
ffi.cdef("bool x86_dec_r32(reg, void**);")
ffi.cdef("bool x86_push_r16(reg, void**);")
ffi.cdef("bool x86_push_r32(reg, void**);")
ffi.cdef("bool x86_pop_r16(reg, void**);")
ffi.cdef("bool x86_pop_r32(reg, void**);")
ffi.cdef("bool x86_pop_r64(reg, void**);")
ffi.cdef("bool x86_pushf(void**);")
ffi.cdef("bool x86_popf(void**);")
ffi.cdef("bool x86_ret(void**);")
